version: '3.5'

services:
    latex:
      build:
        context: .
      volumes:
          - ./latex:/home/latex
      command: bash -c 'make clean && make && pandoc /home/latex/tcc.tex -o /home/latex/tcc.docx'

